// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwe7gZbKjD6Z2TfOlU4KfoaTsch1_pAeI',
    appId: '1:894544806546:web:0409deaec99bba38f85c4b',
    messagingSenderId: '894544806546',
    projectId: 'loginfirebasenew-2ebc4',
    authDomain: 'loginfirebasenew-2ebc4.firebaseapp.com',
    storageBucket: 'loginfirebasenew-2ebc4.firebasestorage.app',
    measurementId: 'G-SVBC37BSZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG86p3hO2ADuJymZff9lSgYVauBoCj72k',
    appId: '1:894544806546:android:45c0ea9b7309e025f85c4b',
    messagingSenderId: '894544806546',
    projectId: 'loginfirebasenew-2ebc4',
    storageBucket: 'loginfirebasenew-2ebc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG7SY_5c-mrlh_rk3SGhEnshJ1HfU-RmU',
    appId: '1:894544806546:ios:93afb1872210d597f85c4b',
    messagingSenderId: '894544806546',
    projectId: 'loginfirebasenew-2ebc4',
    storageBucket: 'loginfirebasenew-2ebc4.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebaseNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG7SY_5c-mrlh_rk3SGhEnshJ1HfU-RmU',
    appId: '1:894544806546:ios:93afb1872210d597f85c4b',
    messagingSenderId: '894544806546',
    projectId: 'loginfirebasenew-2ebc4',
    storageBucket: 'loginfirebasenew-2ebc4.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebaseNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwe7gZbKjD6Z2TfOlU4KfoaTsch1_pAeI',
    appId: '1:894544806546:web:03bfd69dcc2a1c30f85c4b',
    messagingSenderId: '894544806546',
    projectId: 'loginfirebasenew-2ebc4',
    authDomain: 'loginfirebasenew-2ebc4.firebaseapp.com',
    storageBucket: 'loginfirebasenew-2ebc4.firebasestorage.app',
    measurementId: 'G-RH2D4HKLZ0',
  );
}
